# Generated by Django 5.1 on 2024-10-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='doors',
            field=models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('2', '2 Doors'), ('3', '3 Doors (Hatchback)'), ('4', '4 Doors (Sedan/Standard)'), ('5', '5 Doors (SUV/Compact SUV)'), ('6', '6 Doors (Extended SUV/Van)'), ('Sliding', 'Sliding Doors (Minivan/Van)'), ('Gullwing', 'Gullwing Doors (Luxury/Sports Cars)'), ('Falcon Wing', 'Falcon Wing Doors (Tesla Model X)'), ('Butterfly', 'Butterfly Doors (Exotic Sports Cars)'), ('Suicide', 'Suicide Doors (Retro/Luxury Cars)')], max_length=150),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
