# Generated by Django 5.1 on 2024-10-11 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_doors_alter_car_fuel_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='country',
            field=models.CharField(choices=[('IN', 'India'), ('US', 'United States')], default='US', max_length=50),
        ),
    ]
