# Generated by Django 5.1 on 2024-10-11 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_car_state_india_car_state_us_alter_car_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='state_india',
        ),
        migrations.RemoveField(
            model_name='car',
            name='state_us',
        ),
    ]
